# Generated by Django 5.2 on 2025-04-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_security_answer_profile_maiden_name'),
        ('accounts', '0004_alter_mealplan_user_purchase'),
    ]

    operations = [
    ]
